- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
  tags:
    - docker

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Add Docker Repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
  tags:
    - docker

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true
  tags:
    - docker

- name: Ensure group "docker" exists
  ansible.builtin.group:
    name: docker
    state: present
  tags:
    - docker

- name: Add user to docker group
  become: yes
  user:
    name: "{{ lookup('env', 'USER') | default('dev', true) }}"
    groups: docker
    append: yes
  tags:
    - docker
